config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  get 'home/all_services', to: 'home#all_services', as: 'all_services'
  get 'home/show/:id', to: 'home#show', as: :service
  get 'home/book_service/:id', to: 'home#book_service', as: :home_book_service
  post '/payments/create', to: 'payments#create', as: 'payments_create'
  get '/categories/:category_id/services', to: 'services#index', as: 'category_services'

  namespace :customer do
    get 'dashboard/index'
    resources :bookings, only: %i[index new create]
    resources :reviews, only: %i[index create new]
  end

  namespace :admin do
    resources :categories

    resources :dashboard
    resources :services, only: %i[index show update]
  end

  namespace :seller do
    get 'dashboard/index'
    resources :bookings, only: %i[index edit update]
    resources :services do
      member do
        patch 'reapprove'
      end
    end
  end
  devise_for :users, path: '', path_names: { sign_in: 'login' },
                     controllers: { sessions: 'users/sessions', passwords: 'users/passwords' }
end

app/views/shared/_admin_sidebar.html.erb
<nav class="w-64 bg-[#030637] h-full p-4 sidebar-heading">
  <div class="mb-6 text-center">
    <%= link_to root_path do %>
      <%= image_tag('logo-home.svg', class: 'mx-auto h-5') %>
    <% end %>
  </div>
  <ul class="space-y-4 pt-9">
    <li>
      <%= link_to admin_dashboard_index_path, class: 'flex items-center py-2 px-4 text-white hover:bg-gray-700 focus:bg-gray-700 focus:outline-none', id: 'categories-link' do %>
        <i class="fas fa-th-large text-lg mr-2"></i>
        Dashboard
      <% end %>
    </li>
    <li>
      <%= link_to admin_categories_path, class: 'flex items-center py-2 px-4 text-white hover:bg-gray-700 focus:bg-gray-700 focus:outline-none', id: 'categories-link' do %>
        <i class="fas fa-check-circle text-lg mr-2"></i>
        Categories
      <% end %>
    </li>
    <li>
      <%= link_to admin_services_path, class: 'flex items-center py-2 px-4 text-white hover:bg-gray-700 focus:bg-gray-700 focus:outline-none', id: 'service-requests-link' do %>
        <i class="fas fa-tools text-lg mr-2"></i>
        Services
      <% end %>
    </li>
    <!-- Add more options as needed -->
  </ul>
</nav>

app/views/shared/_customer_sidebar.html.erb
<nav class="w-64 bg-[#030637] h-full p-4 sidebar-heading">
  <div class="mb-6 text-center">
    <%= link_to root_path do %>
      <%= image_tag('logo-home.svg', class: 'mx-auto h-5') %>
    <% end %>
  </div>
  <ul class="space-y-4 pt-9">
     <li>
      <%= link_to customer_dashboard_index_path, class: 'flex items-center py-2 px-4 text-white hover:bg-gray-700 focus:bg-gray-700 focus:outline-none', id: 'service-requests-link' do %>
        <i class="fas fa-th-large text-lg mr-2"></i>
        Dashboard
      <% end %>
    </li>
    <li>
      <%= link_to customer_bookings_path, class: 'flex items-center py-2 px-4 text-white hover:bg-gray-700 focus:bg-gray-700 focus:outline-none', id: 'service-requests-link' do %>
        <i class="fas fa-check-circle text-lg mr-2"></i>
        Booked Services
      <% end %>
    </li>
    <li>
      <%= link_to customer_reviews_path, class: 'flex items-center py-2 px-4 text-white hover:bg-gray-700 focus:bg-gray-700 focus:outline-none', id: 'service-requests-link' do %>
        <i class="fas fa-clipboard-list text-lg mr-2"></i>
        Reviews
      <% end %>
    </li>
  </ul>
</nav>

app/views/shared/_flash_messages.html.erb
<div class="flash-msg position-fixed top-0 start-50 w-100">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %> alert-dismissible mb-1">
      <%= value.to_s.html_safe %>
      <button class="btn-close btn-close-black position-absolute top-0 end-0 bottom-0" data-bs-dismiss="alert" data-bs-target=".flash-msg"></button>
    </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer class="container mx-auto bg-white py-8 border-t border-gray-400">
  <div class="container flex px-3 py-8 ">
    <div class="w-full mx-auto flex flex-wrap">
      <div class="flex w-full lg:w-1/2 ">
        <div class="px-3 md:px-0">
          <h3 class="font-bold text-gray-900">About</h3>
          <p class="py-4">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vel mi ut felis tempus commodo nec id erat. Suspendisse consectetur dapibus velit ut lacinia.
          </p>
        </div>
      </div>
      <div class="flex w-full lg:w-1/2 lg:justify-end lg:text-right mt-6 md:mt-0">
        <div class="px-3 md:px-0">
          <h3 class="text-left font-bold text-gray-900">Social</h3>
          <div class="w-full flex items-center py-4 mt-0">
            <a href="#" class="mx-2">
              <svg class="w-6 h-6 fill-current" viewBox="0 0 24 24">
                <path d="M23.953 4.57a10 10 0 01-2.825.775 4.958 4.958 0 002.163-2.723c-.951.555-2.005.959-3.127 1.184a4.92 4.92 0 00-8.384 4.482C7.69 8.095 4.067 6.13 1.64 3.162a4.822 4.822 0 00-.666 2.475c0 1.71.87 3.213 2.188 4.096a4.904 4.904 0 01-2.228-.616v.06a4.923 4.923 0 003.946 4.827 4.996 4.996 0 01-2.212.085 4.936 4.936 0 004.604 3.417 9.867 9.867 0 01-6.102 2.105c-.39 0-.779-.023-1.17-.067a13.995 13.995 0 007.557 2.209c9.053 0 13.998-7.496 13.998-13.985 0-.21 0-.42-.015-.63A9.935 9.935 0 0024 4.59z"></path>
              </svg>
            </a>
            <a href="#" class="mx-2">
              <svg class="w-6 h-6 fill-current" viewBox="0 0 24 24">
                <path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z"></path>
              </svg>
            </a>
            <a href="#" class="mx-2">
              <svg class="w-6 h-6 fill-current" viewBox="0 0 24 24">
                <path d="M12 0C8.74 0 8.333.015 7.053.072 5.775.132 4.905.333 4.14.63c-.789.306-1.459.717-2.126 1.384S.935 3.35.63 4.14C.333 4.905.131 5.775.072 7.053.012 8.333 0 8.74 0 12s.015 3.667.072 4.947c.06 1.277.261 2.148.558 2.913.306.788.717 1.459 1.384 2.126.667.666 1.336 1.079 2.126 1.384.766.296 1.636.499 2.913.558C8.333 23.988 8.74 24 12 24s3.667-.015 4.947-.072c1.277-.06 2.148-.262 2.913-.558.788-.306 1.459-.718 2.126-1.384.666-.667 1.079-1.335 1.384-2.126.296-.765.499-1.636.558-2.913.06-1.28.072-1.687.072-4.947s-.015-3.667-.072-4.947c-.06-1.277-.262-2.149-.558-2.913-.306-.789-.718-1.459-1.384-2.126C21.319 1.347 20.651.935 19.86.63c-.765-.297-1.636-.499-2.913-.558C15.667.012 15.26 0 12 0zm0 2.16c3.203 0 3.585.016 4.85.071 1.17.055 1.805.249 2.227.415.562.217.96.477 1.382.896.419.42.679.819.896 1.381.164.422.36 1.057.413 2.227.057 1.266.07 1.646.07 4.85s-.015 3.585-.074 4.85c-.061 1.17-.256 1.805-.421 2.227-.224.562-.479.96-.899 1.382-.419.419-.824.679-1.38.896-.42.164-1.065.36-2.235.413-1.274.057-1.649.07-4.859.07-3.211 0-3.586-.015-4.859-.074-1.171-.061-1.816-.256-2.236-.421-.569-.224-.96-.479-1.379-.899-.421-.419-.69-.824-.9-1.38-.165-.42-.359-1.065-.42-2.235-.045-1.26-.061-1.649-.061-4.844 0-3.196.016-3.586.061-4.861.061-1.17.255-1.814.42-2.234.21-.57.479-.96.9-1.381.419-.419.81-.689 1.379-.898.42-.166 1.051-.361 2.221-.421 1.275-.045 1.65-.06 4.859-.06l.045.03zm0 3.678c-3.405 0-6.162 2.76-6.162 6.162 0 3.405 2.76 6.162 6.162 6.162 3.405 0 6.162-2.76 6.162-6.162 0-3.405-2.76-6.162-6.162-6.162zM12 16c-2.21 0-4-1.79-4-4s1.79-4 4-4 4 1.79 4 4-1.79 4-4 4zm7.846-10.405c0 .795-.646 1.44-1.44 1.44-.795 0-1.44-.646-1.44-1.44 0-.794.646-1.439 1.44-1.439.793-.001 1.44.645 1.44 1.439z"></path>
              </svg>
            </a>
            <a href="#" class="mx-2">
              <svg class="w-6 h-6 fill-current" viewBox="0 0 24 24">
                <path d="M12.017 0C5.396 0 .029 5.367.029 11.987c0 5.079 3.158 9.417 7.618 11.162-.105-.949-.199-2.403.041-3.439.219-.937 1.406-5.957 1.406-5.957s-.359-.72-.359-1.781c0-1.663.967-2.911 2.168-2.911 1.024 0 1.518.769 1.518 1.688 0 1.029-.653 2.567-.992 3.992-.285 1.193.6 2.165 1.775 2.165 2.128 0 3.768-2.245 3.768-5.487 0-2.861-2.063-4.869-5.008-4.869-3.41 0-5.409 2.562-5.409 5.199 0 1.033.394 2.143.889 2.741.099.12.112.225.085.345-.09.375-.293 1.199-.334 1.363-.053.225-.172.271-.401.165-1.495-.69-2.433-2.878-2.433-4.646 0-3.776 2.748-7.252 7.92-7.252 4.158 0 7.392 2.967 7.392 6.923 0 4.135-2.607 7.462-6.233 7.462-1.214 0-2.354-.629-2.758-1.379l-.749 2.848c-.269 1.045-1.004 2.352-1.498 3.146 1.123.345 2.306.535 3.55.535 6.607 0 11.985-5.365 11.985-11.987C23.97 5.39 18.592.026 11.985.026L12.017 0z"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<header class="fixed w-full z-50">
  <nav class="bg-[#030637] border-gray-200 py-2.5 dark:bg-gray-900">
    <div class="container mx-auto flex items-center justify-between px-4">
      <a href="<%= root_path %>" class="flex items-center">
        <%= image_tag("logo-home.svg", alt: "Homely Help Icon", class: "navbar-logo h-6") %>
      </a>
      <%= form_tag(all_services_path, method: :get, class: "md:flex items-center") do %>
        <%= text_field_tag :search, params[:search], class: "px-2 py-1 border border-gray-300 rounded-md focus:outline-none focus:border-purple-700 bg-gray-100 text-sm", placeholder: "Search..." %>
        <%= submit_tag "Search", class: "px-4 py-2 bg-[#910A67] text-white rounded-md ml-2" %>
      <% end %>
      <ul class="flex items-center space-x-4 lg:space-x-8">
        <li>
          <%= link_to("Home", root_path, class: "nav-link") %>
        </li>
        <% if user_signed_in? %>
          <% if current_user.admin? %>
            <%= link_to("Admin", admin_dashboard_index_path, class: "nav-link") %>
          <% elsif current_user.seller? %>
            <%= link_to("Seller", seller_dashboard_index_path, class: "nav-link") %>
          <% else %>
            <%= link_to("Customer", customer_dashboard_index_path, class: "nav-link") %>
          <% end %>
        <% end %>
        <li>
          <%= link_to("Services", all_services_path, class: "nav-link") %>
        </li>
      </ul>
        <div>
          <% if user_signed_in? %>
            <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: "px-4 py-2 bg-[#910A67] bg-red-500 text-white rounded-md hover:bg-red-600 focus:outline-none focus:shadow-outline-red active:bg-red-800 btn-logout" %>
          <% else %>
            <%= link_to "Log In", new_user_session_path, class: "px-4 py-2 bg-[#910A67] text-white rounded-md hover:bg-[#7A0958] focus:outline-none focus:shadow-outline-purple active:bg-[#5E0844] btn-login" %>
          <% end %>
        </div>
    </div>
  </nav>
</header>

app/views/shared/_seller_sidebar.html.erb
<nav class="w-64 bg-[#030637] h-full p-4 sidebar-heading">
  <div class="mb-6 text-center">
    <%= link_to root_path do %>
      <%= image_tag('logo-home.svg', class: 'mx-auto h-5') %>
    <% end %>
  </div>
  <ul class="space-y-4 pt-9">
      <li>
      <%= link_to seller_dashboard_index_path, class: 'flex items-center py-2 px-4 text-white hover:bg-gray-700 focus:bg-gray-700 focus:outline-none', id: 'service-requests-link' do %>
        <i class="fas fa-check-circle text-lg mr-2"></i>
        Booked Services
      <% end %>
    </li>
    <li>
      <%= link_to  seller_services_path, class: 'flex items-center py-2 px-4 text-white hover:bg-gray-700 focus:bg-gray-700 focus:outline-none', id: 'service-requests-link' do %>
        <i class="fas fa-tools text-lg mr-2"></i>
        Services
      <% end %>
    </li>
  </ul>
</nav>
                                                                                                                                                                                                                                                                                                                                                                                                                                            