config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  get 'home/all_services', to: 'home#all_services', as: 'all_services'
  get 'home/show/:id', to: 'home#show', as: :service
  get 'home/book_service/:id', to: 'home#book_service', as: :home_book_service
  post '/payments/create', to: 'payments#create', as: 'payments_create'
  get '/categories/:category_id/services', to: 'services#index', as: 'category_services'

  namespace :customer do
    get 'dashboard/index'
    resources :bookings, only: %i[index new create]
    resources :reviews, only: %i[index create new]
  end

  namespace :admin do
    resources :categories

    resources :dashboard
    resources :services, only: %i[index show update]
  end

  namespace :seller do
    get 'dashboard/index'
    resources :bookings, only: %i[index edit update]
    resources :services do
      member do
        patch 'reapprove'
      end
    end
  end
  devise_for :users, path: '', path_names: { sign_in: 'login' },
                     controllers: { sessions: 'users/sessions', passwords: 'users/passwords' }
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @services = Service.where(status: 'approved')
  end

  def all_services
    @categories = Category.all

    if params[:category_id].present?
      @selected_category = Category.find(params[:category_id])
      @services = @selected_category.services.where(status: 'approved')
    else
      @services = Service.where(status: 'approved')
    end
  end

  def show
    @service = Service.find(params[:id])
  end

  def book_service
    @service = Service.find(params[:id])
    @booking = current_user.bookings.new(service: @service)

    if @booking.save
      redirect_to root_path, notice: 'Service booked successfully.'
    else
      redirect_to root_path, alert: 'Failed to book the service.'
    end
  end
end

app/views/home/_services.html.erb
<%= turbo_frame_tag "my-categeory" do %>
<div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-4 gap-4">
  <% @services.each do |service| %>
    <div class="mx-2 mt-4 flex flex-col rounded-lg bg-white shadow-[0_2px_15px_-3px_rgba(0,0,0,0.07),0_10px_20px_-2px_rgba(0,0,0,0.04)] dark:bg-neutral-700">
      <div class="relative overflow-hidden rounded-t-lg" style="padding-top: 60%;">
        <%= image_tag service.avatar, class: "absolute inset-0 w-full h-full object-cover" if service.avatar.attached? %>
      </div>
      <div class="p-4 flex flex-col">
        <h5 class="mb-2 text-lg font-medium leading-tight text-neutral-800 dark:text-neutral-50">
          <%= service.title %>
        </h5>
        <p class="mb-2 text-base text-neutral-600 dark:text-neutral-200">
          <%= truncate(service.description, length: 80) %>
        </p>
        <div class="flex-grow"></div>
        <div class="flex justify-between items-center border-t-2 border-neutral-100 px-2 py-2 dark:border-neutral-600 dark:text-neutral-50">
          <div class="flex">
            <%= link_to 'Show',service_path(service), class: 'text-blue-500 underline mr-2' %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<% end %>

app/views/home/all_services.html.erb
<div class="dashboard-container">
  <div class="container mx-auto p-4 mb-48">
    <h2 class="text-2xl font-semibold mb-4 text-neutral-800 dark:text-neutral-50">Services</h2>
    <%= turbo_frame_tag "catageory" do %>
      <div class="flex mb-4 space-x-4">
        <% @categories.each do |category| %>
          <%= link_to category.name, all_services_path(category_id: category.id), class: "bg-blue-500 text-white px-4 py-2 rounded", data: { turbo_frame: "my-category"} %>
        <% end %>
      </div>
      <%= render "services", services: @services %>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<section class="bg-white dark:bg-gray-900">
  <div class="grid max-w-screen-xl px-4 pt-20 pb-2 mx-auto lg:gap-8 xl:gap-0 lg:py-16 lg:grid-cols-12 lg:pt-28">
    <div class="mr-auto place-self-center lg:col-span-7">
      <h1 class="max-w-2xl mb-4 text-5xl font-extrabold leading-none tracking-tight md:text-6xl xl:text-7xl text-[#030637]">Your Comfort, <br>
        Our Commitment. </h1>
      <p class="max-w-2xl mb-6 font-light text-gray-500 lg:mb-8 md:text-lg lg:text-xl dark:text-gray-400">Bringing Quality Home Services to Your Doorstep. </p>
      <div class="space-y-4 sm:flex sm:space-y-0 sm:space-x-4">
        <a href="/home/all_services" class="inline-flex items-center justify-center w-full px-5 py-3 text-sm font-medium text-center text-gray-900 border border-gray-200 rounded-lg sm:w-auto hover:bg-gray-100 focus:ring-4 focus:ring-gray-100 dark:text-white dark:border-gray-700 dark:hover:bg-gray-700 dark:focus:ring-gray-800">
          <svg class="w-4 h-4 mr-2 text-gray-500 dark:text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 496 512"></svg>Explore Services
        </a>
      </div>
    </div>
    <div class="lg:mt-0 lg:col-span-5 lg:flex">
      <%= image_tag("service.jpg", alt: "hero image", class: "w-full h-auto") %>
    </div>
  </div>
</section>
<div class="bg-white text-gray-600 work-sans leading-normal text-base tracking-normal">
  <section class="bg-white py-8">
    <div class="container mx-auto flex items-center flex-wrap pt-4 pb-12">
      <nav id="store" class="w-full z-30 top-0 px-6 py-1">
        <div class="w-full container mx-auto flex flex-wrap items-center justify-between mt-0 px-2 py-3">
          <a class="uppercase tracking-wide no-underline hover:no-underline font-bold text-gray-800 text-xl " href="#">
            Store
          </a>
          <div class="flex items-center" id="store-nav-content">
            <a class="pl-3 inline-block no-underline hover:text-black" href="#">
              <svg class="fill-current hover:text-black" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                <path d="M7 11H17V13H7zM4 7H20V9H4zM10 15H14V17H10z" />
              </svg>
            </a>
            <a class="pl-3 inline-block no-underline hover:text-black" href="#">
              <svg class="fill-current hover:text-black" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                <path d="M10,18c1.846,0,3.543-0.635,4.897-1.688l4.396,4.396l1.414-1.414l-4.396-4.396C17.365,13.543,18,11.846,18,10 c0-4.411-3.589-8-8-8s-8,3.589-8,8S5.589,18,10,18z M10,4c3.309,0,6,2.691,6,6s-2.691,6-6,6s-6-2.691-6-6S6.691,4,10,4z" />
              </svg>
            </a>
          </div>
        </div>
      </nav>
      <div class="flex flex-wrap -mx-4">
        <% @services.each do |service| %>
          <div class="w-full md:w-1/3 xl:w-1/4 p-6 flex flex-col">
            <a href="#">
              <% if service.avatar.present? %>
                <%= image_tag(service.avatar, alt: "Product Image", class: "hover:grow hover:shadow-lg object-cover w-full h-48 rounded-md") %>
              <% end %>
              <div class="pt-3 flex items-center justify-between">
                <p class=""><%= service.title %></p>
                <%= link_to 'Book Now', service_path(service), class:"bg-[#910A67] text-white px-4 py-2 rounded-md hover:bg-[#7A0958] focus:outline-none focus:shadow-outline-purple active:bg-[#5E0844]" %>
              </div>
              <p class="pt-1 text-gray-900"><%= number_to_currency(service.price, unit: '£') %></p>
            </a>
          </div>
        <% end %>
      </div>
    </div>
  </section>
  <section class="bg-white py-8">
    <div class="container py-8 px-6 mx-auto">
      <a class="uppercase tracking-wide no-underline hover:no-underline font-bold text-gray-800 text-xl mb-8" href="#">
        About
      </a>
      <p class="mt-8 mb-8">This template is inspired by the stunning nordic minimalist design - in particular:
        <br>
        <a class="text-gray-800 underline hover:text-gray-900" href="http://savoy.nordicmade.com/" target="_blank">Savoy Theme</a> created by <a class="text-gray-800 underline hover:text-gray-900" href="https://nordicmade.com/">https://nordicmade.com/</a> and <a class="text-gray-800 underline hover:text-gray-900" href="https://www.metricdesign.no/" target="_blank">https://www.metricdesign.no/</a></p>
      <p class="mb-8">Lorem ipsum dolor sit amet, consectetur <a href="#">random link</a> adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat. Vitae aliquet nec ullamcorper sit. Nullam eget felis eget nunc lobortis mattis aliquam. In est ante in nibh mauris. Egestas congue quisque egestas diam in. Facilisi nullam vehicula ipsum a arcu. Nec nam aliquam sem et tortor consequat. Eget mi proin sed libero enim sed faucibus turpis in. Hac habitasse platea dictumst quisque. In aliquam sem fringilla ut. Gravida rutrum quisque non tellus orci ac auctor augue mauris. Accumsan lacus vel facilisis volutpat est velit egestas dui id. At tempor commodo ullamcorper a. Volutpat commodo sed egestas egestas fringilla. Vitae congue eu consequat ac.</p>
    </div>
  </section>
</div>

app/views/home/show.html.erb
<%= turbo_frame_tag "my-category" do %>
  <div class="dashboard-container">
    <div class="container mx-auto p-4 mb-48">
      <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div class="mb-4 md:mb-0">
          <%= image_tag(@service.avatar, alt: "Product Image", class: "w-full h-auto md:w-96 rounded-lg border") %>
        </div>
        <div class="pt-8">
          <h1 class="text-3xl font-bold mb-2"><%= @service.title %></h1>
          <p class="text-lg font-semibold mb-2">Price: <%= number_to_currency(@service.price, unit: '£') %></p>
          <p class="text-gray-700 mb-4"><%= @service.description %></p>
          <%= form_tag(payments_create_path(service_id: @service.id), method: 'post') do %>
            <script
              src="https://checkout.stripe.com/checkout.js" class="stripe-button"
              data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
              data-name="<%= @service.title %>"
              data-description="Payment for <%= @service.title %>"
              data-amount="<%= (@service.price * 100).to_i %>"
              data-currency="usd"
              data-locale="auto"
              data-zip-code="false"
              data-email="<%= current_user.email %>"
            ></script>
          <% end %>
        </div>
      </div>
      <!-- Display reviews for the service -->
      <div class="mt-8">
        <h2 class="text-2xl font-semibold mb-4">Reviews</h2>
        <% if @service.reviews.any? %>
          <ul>
            <% total_ratings = @service.reviews.sum(:rating).to_f %>
            <% average_rating = total_ratings / @service.reviews.count %>
            <div class="flex items-center mb-2">
              <% (1..5).each do |i| %>
                <svg class="w-4 h-4 <%= i <= average_rating ? 'text-yellow-300' : 'text-gray-300 dark:text-gray-500' %> me-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                  <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                </svg>
              <% end %>
              <p class="ms-1 text-sm font-medium text-gray-500 dark:text-gray-400"><%= format('%.2f', average_rating) %></p>
              <p class="ms-1 text-sm font-medium text-gray-500 dark:text-gray-400">out of 5</p>
            </div>
            <% @service.reviews.each do |review| %>
              <li>
                <strong>Rating:</strong>
                <div class="flex items-center">
                  <% (1..5).each do |i| %>
                    <svg class="w-4 h-4 <%= i <= review.rating ? 'text-yellow-300' : 'text-gray-300 dark:text-gray-500' %> me-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                      <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                    </svg>
                  <% end %>
                </div>
                |
                <strong>Comment:</strong> <%= review.comment %>
              </li>
            <% end %>
          </ul>
        <% else %>
          <p>No reviews yet.</p>
        <% end %>
      </div>
    </div>
  </div>
<% end %>