config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  get 'home/all_services', to: 'home#all_services', as: 'all_services'
  get 'home/show/:id', to: 'home#show', as: :service
  get 'home/book_service/:id', to: 'home#book_service', as: :home_book_service
  post '/payments/create', to: 'payments#create', as: 'payments_create'
  get '/categories/:category_id/services', to: 'services#index', as: 'category_services'

  namespace :customer do
    get 'dashboard/index'
    resources :bookings, only: %i[index new create]
    resources :reviews, only: %i[index create new]
  end

  namespace :admin do
    resources :categories

    resources :dashboard
    resources :services, only: %i[index show update]
  end

  namespace :seller do
    get 'dashboard/index'
    resources :bookings, only: %i[index edit update]
    resources :services do
      member do
        patch 'reapprove'
      end
    end
  end
  devise_for :users, path: '', path_names: { sign_in: 'login' },
                     controllers: { sessions: 'users/sessions', passwords: 'users/passwords' }
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
  has_many :services, dependent: :destroy
end

app/controllers/admin/categories_controller.rb
# frozen_string_literal: true

module Admin
  class CategoriesController < Admin::DashboardController
    before_action :authenticate_admin!
    before_action :set_category, only: %i[destroy]

    def index
      @categories = Category.all
    end

    def new
      @category = Category.new
    end

    def create
      @category = current_user.categories.new(category_params)

      if @category.save
        redirect_to admin_categories_path, notice: 'Category was successfully created.'
      else
        render :new
      end
    end

    def destroy
      @category.destroy

      redirect_to admin_categories_path, notice: 'Category was successfully deleted.'
    end

    private

    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :user_id)
    end
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
end

app/views/admin/categories/_form.html.erb
<div class="container mx-auto p-4">
  <%= form_with(model: @category, url: admin_categories_path, method: :post, class: 'max-w-md mx-auto bg-white p-8 border rounded shadow-md') do |form| %>
    <% if @category.errors.any? %>
      <div id="error_explanation" class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative">
        <h2 class="text-sm font-semibold"><%= pluralize(@category.errors.count, 'error') %> prohibited this category from being saved:</h2>
        <ul class="list-disc list-inside">
          <% @category.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="mb-4">
      <%= form.label :name, class: 'block text-gray-700 text-sm font-bold mb-2' %>
      <%= form.text_field :name, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline', required: true  %>
    </div>
    <div class="mb-6">
      <%= form.submit "Save", class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline' %>
    </div>
  <% end %>
</div>

app/views/admin/categories/index.html.erb
<div class="container mx-auto p-4 bg-[#030637] border rounded-lg shadow-lg">
  <h1 class="text-3xl font-bold mb-4 text-white">Admin Categories</h1>
  <table class="min-w-full border rounded-lg overflow-hidden">
    <thead class="bg-yellow-800 text-white">
      <tr>
        <th class="py-2 px-4">Name</th>
        <th class="py-2 px-4">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td class="py-2 px-4 text-white"><%= category.name %></td>
          <td class="py-2 px-4">
            <%= button_to 'Delete', admin_category_path(category), method: :delete, class: 'text-white hover:underline'%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="mt-4">
    <%= link_to 'New Category', new_admin_category_path, class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded' %>
  </div>
</div>

app/views/admin/categories/new.html.erb
<div class="container flex justify-center items-center ">
  <div class="text-center">
    <h1 class="text-3xl font-bold mb-4 text-white">New Category</h1>
    <%= render 'form' %>
    <%= link_to 'Back', admin_categories_path, class: 'bg-yellow-500 hover:bg-yellow-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline' %>
  </div>
</div>