config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  get 'home/all_services', to: 'home#all_services', as: 'all_services'
  get 'home/show/:id', to: 'home#show', as: :service
  get 'home/book_service/:id', to: 'home#book_service', as: :home_book_service
  post '/payments/create', to: 'payments#create', as: 'payments_create'
  get '/categories/:category_id/services', to: 'services#index', as: 'category_services'

  namespace :customer do
    get 'dashboard/index'
    resources :bookings, only: %i[index new create]
    resources :reviews, only: %i[index create new]
  end

  namespace :admin do
    resources :categories

    resources :dashboard
    resources :services, only: %i[index show update]
  end

  namespace :seller do
    get 'dashboard/index'
    resources :bookings, only: %i[index edit update]
    resources :services do
      member do
        patch 'reapprove'
      end
    end
  end
  devise_for :users, path: '', path_names: { sign_in: 'login' },
                     controllers: { sessions: 'users/sessions', passwords: 'users/passwords' }
end

app/models/service.rb
# frozen_string_literal: true

class Service < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  enum status: { pending: 'pending', approved: 'approved', rejected: 'rejected', reapproval: 'reapproval' }
  has_one_attached :avatar, dependent: :destroy
  # validates_presence_of :title, :description, :user_id, :category_id
end

app/controllers/admin/services_controller.rb
# frozen_string_literal: true

class Admin::ServicesController < Admin::DashboardController
  before_action :authenticate_admin!
  before_action :set_service, only: [:update]

  def index
    @services = Service.all
    # @reapproval_requests = Service.where(status: 'reapproval')
  end

  def update
    if @service.update(service_params)
      if @service.rejected?
        redirect_to admin_services_path, notice: 'Service rejected successfully.'
      else
        redirect_to admin_services_path, notice: 'Service status updated successfully.'
      end
    else
      redirect_to admin_services_path, alert: 'Failed to update service status.'
    end
  end

  private

  def set_service
    @service = Service.find(params[:id])
  end

  def service_params
    params.require(:service).permit(:status, :rejection_reason, :reapproval_request)
  end
end

app/controllers/seller/bookings_controller.rb
class BookingsController < Seller::DashboardController
  # before_action :authenticate_seller!

  def index
    @approved_bookings = Booking.where(status: 'booked')
  end
end

app/controllers/seller/dashboard_controller.rb
# frozen_string_literal: true

module Seller
  class DashboardController < ApplicationController
    layout 'seller_dashboard'
    include Pagy::Backend

    def index
      @approved_bookings = Booking.where(status: 'booked')
    end
  end
end

app/controllers/seller/services_controller.rb
class Seller::ServicesController < Seller::DashboardController
  before_action :authenticate_seller!, only: %i[create destroy]
  before_action :set_service, only: %i[show destroy reapprove edit update]

  def index
    @pagy_approved, @approved_services = pagy(Service.where(status: 'approved'))
    @pagy_pending, @pending_services = pagy(Service.where(status: 'pending'))
    @pagy_rejected, @rejected_services = pagy(Service.where(status: 'rejected'))
    @pagy_reapproval, @reapproval_request = pagy(Service.where(status: 'reapproval'))
  end

  def show
    @reviews = @service.reviews
  end

  def new
    @service = current_user.services.build
  end

  def edit; end

  def create
    @service = current_user.services.build(service_params.merge(status: 'pending'))

    if @service.save
      redirect_to seller_services_path, notice: 'Service was successfully created.'
    else
      render :new
    end
  end

  def update
    if @service.update(service_params)
      redirect_to seller_services_path, notice: 'Service was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @service.destroy
    redirect_to seller_services_path, notice: 'Service was successfully deleted.'
  end

  def reapprove
    @services = Service.where(status: 'rejected')

    @service.update(status: 'reapproval', reapproval_request: params[:service][:reapproval_request])

    redirect_to seller_services_path, notice: 'Reapproval request sent successfully.'
  end

  private

  def set_service
    @service = current_user.services.find(params[:id])
  end

  def service_params
    params.require(:service).permit(:title, :description, :category_id, :price, :reapproval_request, :rejection_reason, :avatar)
  end
end

app/views/seller/services/_bookings.html.erb
<!-- _bookings.html.erb-->
<div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-4 mt-8">
  <% services.each do |service| %>
    <div class="mx-2 mt-4 flex flex-col rounded-lg bg-white shadow-[0_2px_15px_-3px_rgba(0,0,0,0.07),0_10px_20px_-2px_rgba(0,0,0,0.04)] dark:bg-neutral-700">
      <a href="<%= seller_service_path(service) %>">
        <div class="relative overflow-hidden rounded-t-lg" style="padding-top: 60%;">
          <%= image_tag service.avatar, class: "absolute inset-0 w-full h-full object-cover" if service.avatar.attached? %>
        </div>
      </a>
      <div class="p-4 flex flex-col">
        <h5 class="mb-2 text-lg font-medium leading-tight text-neutral-800 dark:text-neutral-50">
          <%= service.title %>
        </h5>
        <p class="mb-2 text-base text-neutral-600 dark:text-neutral-200">
          <%= truncate(service.description, length: 80) %>
        </p>
        <div class="flex-grow"></div>
        <div class="flex justify-between items-center border-t-2 border-neutral-100 px-2 py-2 dark:border-neutral-600 dark:text-neutral-50">
          <span>Status: <%= service.status %></span>
          <div>
            <%= link_to 'Show', seller_service_path(service), class: 'text-blue-500 underline mr-2' %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/seller/services/_form.html.erb
<div class="bg-white-100 flex flex-col justify-center sm:py-4">
  <div class="relative py-3 sm:max-w-md sm:mx-auto">
    <div class="absolute inset-0 bg-gradient-to-r from-blue-300 to-blue-600 shadow-lg transform -skew-y-6 sm:skew-y-0 sm:-rotate-6 sm:rounded-3xl"></div>
    <div class="relative px-4 py-6 bg-white shadow-lg sm:rounded-3xl sm:p-8">
      <div class="max-w-md mx-auto">
          <div class="mb-2">
            <%= form.label :title, class: 'block text-gray-700 text-sm font-bold mb-1' %>
            <%= form.text_field :title, class: 'form-input', required: true  %>
          </div>
          <div class="mb-2">
            <%= form.label :description, class: 'block text-gray-700 text-sm font-bold mb-1' %>
            <%= form.text_area :description, class: 'form-input', required: true  %>
          </div>
          <div class="mb-2">
            <%= form.label :category_id, class: 'block text-gray-700 text-sm font-bold mb-1' %><br>
            <%= form.collection_select :category_id, Category.all, :id, :name, { prompt: 'Select a category' }, class: 'form-select', required: true  %>
          </div>
          <div class="mb-2">
            <%= form.label :price, class: 'block text-gray-700 text-sm font-bold mb-1' %><br>
            <%= form.number_field :price, class: 'form-input', required: true  %>
          </div>
          <div class="mb-2">
            <%= form.label :avatar, class: 'block text-gray-700 text-sm font-bold mb-1' %><br>
            <%= form.file_field :avatar, direct_upload: true, data: { previews_target: "input", action: "change->previews#preview" }, class: 'form-input', required: true  %>
          </div>
          <div class="mb-4">
          <%= form.submit 'Save', class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline' %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/seller/services/_image_preview.html.erb
<div class="image-container">
  <% if service.avatar.attached? %>
    <%= image_tag service.avatar, data: { previews_target: "preview" }, class: "w-64 h-64" %>
  <% else %>
    <%= image_tag "", data: { previews_target: "preview" }, class: "image" %>
  <% end %>
</div>
</div>

app/views/seller/services/edit.html.erb
<div class="container flex justify-center items-center">
  <div class="text-center">
    <h1 class="text-3xl font-bold mb-4 text-white">Edit Category</h1>
    <%= form_with(model: @service, url: seller_service_path(@service), method: :patch, class: 'py-4 text-base leading-6 space-y-2 text-gray-700 sm:text-lg sm:leading-7') do |form| %>
      <%= render 'form', form: form %>
    <% end %>
    <%= link_to 'Back', seller_dashboard_index_path, class: 'bg-yellow-500 hover:bg-yellow-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline' %>
  </div>
</div>

app/views/seller/services/index.html.erb
<div class="dashboard-container">
  <div class="absolute top-20 right-60 p-4">
    <%= link_to 'Create New Service', new_seller_service_path, class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded inline-block transition duration-300 ease-in-out transform hover:-translate-y-1' %>
  </div>
 <div class="p-8" data-controller="booking">
    <div class="mb-4">
      <button data-action="click->booking#showAllBookings" class="btn btn-primary mr-2">Approved Bookings</button>
      <button data-action="click->booking#showBookingRequests" class="btn btn-primary">Booking Requests</button>
      <button data-action="click->booking#showRejectedBookings" class="btn btn-primary">Rejected Requests</button>
      <button data-action="click->booking#showReapprovalRequests" class="btn btn-primary">Reapproval Requests</button>
    </div>

    <div id="allBookings" class="booking-table">
      <%= turbo_stream.append "allBookings" do %>
        <%= render partial: 'bookings', locals: { services: @approved_services, pagy: @pagy_approved } %>
        <%== pagy_bootstrap_nav(@pagy_approved) if @pagy_approved.pages > 1 %>
      <% end %>
    </div>

    <div id="bookingRequests" class="booking-table" style="display: none;">
      <%= turbo_stream.append "bookingRequests" do %>
        <%= render partial: 'bookings', locals: { services: @pending_services, pagy: @pagy_pending } %>
        <%== pagy_bootstrap_nav(@pagy_pending) if @pagy_pending.pages > 1 %>
      <% end %>
    </div>

    <div id="rejectedBookings" class="booking-table" style="display: none;">
      <%= turbo_stream.append "rejectedBookings" do %>
        <%= render partial: 'bookings', locals: { services: @rejected_services, pagy: @pagy_rejected } %>
        <%== pagy_bootstrap_nav(@pagy_rejected) if @pagy_rejected.pages > 1 %>
      <% end %>
    </div>

    <div id="reapprovalRequests" class="booking-table" style="display: none;">
      <%= turbo_stream.append "reapprovalRequests" do %>
        <%= render partial: 'bookings', locals: { services: @reapproval_request, pagy: @pagy_reapproval } %>
        <%== pagy_bootstrap_nav(@pagy_reapproval) if @pagy_reapproval.pages > 1 %>
      <% end %>
    </div>
  </div>
</div>

app/views/seller/services/new.html.erb
<div class="container flex justify-center items-center">
  <div class="text-center">
    <h1 class="text-3xl font-bold mb-4 text-white">New Category</h1>
    <%= form_with(model: @service, url: seller_services_path, method: :post, class: 'py-4 text-base leading-6 space-y-2 text-gray-700 sm:text-lg sm:leading-7') do |form| %>
      <%= render 'form', form: form %>
    <% end %>
    <%= link_to 'Back', seller_dashboard_index_path, class: 'bg-yellow-500 hover:bg-yellow-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline' %>
  </div>
</div>

app/views/seller/services/show.html.erb
<div class="bg-blue-500 p-8 text-white">
  <h1 class="text-3xl font-bold mb-4">Service Details</h1>
  <p class="mb-2"><%= @service.title %> - Status: <%= @service.status %></p>
  <% if @service.rejected? %>
    <%= link_to 'Edit', edit_seller_service_path(@service), class: 'bg-yellow-500 hover:bg-yellow-700 text-white font-bold py-2 px-3 rounded inline-block transition duration-300 ease-in-out transform hover:-translate-y-1 ml-2' %>
    <%= form_with(model: @service, url: reapprove_seller_service_path(@service), method: :patch, class: 'inline-block') do |form| %>
      <%= form.text_area :reapproval_request, class: 'resize-none shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline mr-2', placeholder: 'Comment for Reapproval Request' %>
      <%= form.submit 'Reapprove', class: 'bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-3 rounded inline-block transition duration-300 ease-in-out transform hover:-translate-y-1' %>
    <% end %>
  <% end %>
  <% @reviews.each do |review| %>
    <p class="mb-2"><%= review.comment %></p>
  <% end %>
</div>